# Stata Kernel Example

- Author: Wenzhi Ding
- Date: 2022-07-06

This notebook is to provide an example of using [Stata Kernel](https://kylebarron.dev/stata_kernel/) in Jupyter.

Actually, this is nothing different from the way we usually use Stata, except for a few iPython Magic Commands (e.g. `%head`).

In [1]:
sysuse auto, clear

(1978 automobile data)

In [2]:
%head 5

     +-----------------------------------------------------------------+
  1. | make          | price | mpg | rep78 | headroom | trunk | weight |
     | AMC Concord   | 4,099 |  22 |     3 |      2.5 |    11 |  2,930 |
     |-----------------------------------------------------------------|
     |  length   |  turn   |  displa~t   |   gear_r~o   |    foreign   |
     |     186   |    40   |       121   |       3.58   |   Domestic   |
     +-----------------------------------------------------------------+

     +-----------------------------------------------------------------+
  2. | make          | price | mpg | rep78 | headroom | trunk | weight |
     | AMC Pacer     | 4,749 |  17 |     3 |      3.0 |    11 |  3,350 |
     |-----------------------------------------------------------------|
     |  length   |  turn   |  displa~t   |   gear_r~o   |    foreign   |
     |     173   |    40   |       258   |       2.53   |   Domestic   |
     +-----------------------------------------------------------------+

     +-----------------------------------------------------------------+
  3. | make          | price | mpg | rep78 | headroom | trunk | weight |
     | AMC Spirit    | 3,799 |  22 |     . |      3.0 |    12 |  2,640 |
     |-----------------------------------------------------------------|
     |  length   |  turn   |  displa~t   |   gear_r~o   |    foreign   |
     |     168   |    35   |       121   |       3.08   |   Domestic   |
     +-----------------------------------------------------------------+

     +-----------------------------------------------------------------+
  4. | make          | price | mpg | rep78 | headroom | trunk | weight |
     | Buick Century | 4,816 |  20 |     3 |      4.5 |    16 |  3,250 |
     |-----------------------------------------------------------------|
     |  length   |  turn   |  displa~t   |   gear_r~o   |    foreign   |
     |     196   |    40   |       196   |       2.93   |   Domestic   |
     +-----------------------------------------------------------------+

     +-----------------------------------------------------------------+
  5. | make          | price | mpg | rep78 | headroom | trunk | weight |
     | Buick Electra | 7,827 |  15 |     4 |      4.0 |    20 |  4,080 |
     |-----------------------------------------------------------------|
     |  length   |  turn   |  displa~t   |   gear_r~o   |    foreign   |
     |     222   |    43   |       350   |       2.41   |   Domestic   |
     +-----------------------------------------------------------------+

In [3]:
%head 5 if trunk >= 20

     +--------------------------------------------------------------------+
  5. | make            |  price | mpg | rep78 | headroom | trunk | weight |
     | Buick Electra   |  7,827 |  15 |     4 |      4.0 |    20 |  4,080 |
     |--------------------------------------------------------------------|
     |   length   |   turn   |   displa~t   |   gear_r~o   |    foreign   |
     |      222   |     43   |        350   |       2.41   |   Domestic   |
     +--------------------------------------------------------------------+

     +--------------------------------------------------------------------+
  6. | make            |  price | mpg | rep78 | headroom | trunk | weight |
     | Buick LeSabre   |  5,788 |  18 |     3 |      4.0 |    21 |  3,670 |
     |--------------------------------------------------------------------|
     |   length   |   turn   |   displa~t   |   gear_r~o   |    foreign   |
     |      218   |     43   |        231   |       2.73   |   Domestic   |
     +--------------------------------------------------------------------+

     +--------------------------------------------------------------------+
 11. | make            |  price | mpg | rep78 | headroom | trunk | weight |
     | Cad. Deville    | 11,385 |  14 |     3 |      4.0 |    20 |  4,330 |
     |--------------------------------------------------------------------|
     |   length   |   turn   |   displa~t   |   gear_r~o   |    foreign   |
     |      221   |     44   |        425   |       2.28   |   Domestic   |
     +--------------------------------------------------------------------+

     +--------------------------------------------------------------------+
 15. | make            |  price | mpg | rep78 | headroom | trunk | weight |
     | Chev. Impala    |  5,705 |  16 |     4 |      4.0 |    20 |  3,690 |
     |--------------------------------------------------------------------|
     |   length   |   turn   |   displa~t   |   gear_r~o   |    foreign   |
     |      212   |     43   |        250   |       2.56   |   Domestic   |
     +--------------------------------------------------------------------+

     +--------------------------------------------------------------------+
 23. | make            |  price | mpg | rep78 | headroom | trunk | weight |
     | Dodge St. Regis |  6,342 |  17 |     2 |      4.5 |    21 |  3,740 |
     |--------------------------------------------------------------------|
     |   length   |   turn   |   displa~t   |   gear_r~o   |    foreign   |
     |      220   |     46   |        225   |       2.94   |   Domestic   |
     +--------------------------------------------------------------------+

In [4]:
reg price mpg headroom trunk

      Source |       SS           df       MS      Number of obs   =        74
-------------+----------------------------------   F(3, 70)        =      7.46
       Model |   153861671         3  51287223.7   Prob > F        =    0.0002
    Residual |   481203725        70  6874338.93   R-squared       =    0.2423
-------------+----------------------------------   Adj R-squared   =    0.2098
       Total |   635065396        73  8699525.97   Root MSE        =    2621.9

------------------------------------------------------------------------------
       price | Coefficient  Std. err.      t    P>|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
         mpg |  -224.3597   65.27511    -3.44   0.001    -354.5468   -94.17263
    headroom |   -659.463   484.5101    -1.36   0.178    -1625.788    306.8619
       trunk |   126.6049   107.2399     1.18   0.242    -87.27846    340.4882
       _cons |   11175.77   2431.134     4.60   0.000     6327.029    16024.52
------------------------------------------------------------------------------